
billspaymentsandrefundperuserindate = Bills payments and refund per user

to2 = To

cashier = Cashier

payments = Payments

refunds = Refunds

deposit = Deposit

totals = Totals

of = Of

page = Page

inDate = In Date