Title = INVOICE REPORT BY DISCOUNT FROM

To = To

BillID = ID

Date = Date

Patient = Patient

Amount = Amount

Paid = Paid

Refunded = Refunded

Balance = Balance

Lastpayment = Last Payment

Totals = Totals

Page = Page

of = of