misscatho = MADA HELVETIC FOUNDATION

autor = I, the undersigned

bdate = Born on

at = at

birthcertificatenum = Birth certificate No.

id = National ID No.

iborn = Having given birth at the maternity ward of the Mada Helvetic Hospital

dateborn = Date of birth

icertify = Certify on my honor that I have declared my exact identity and presented my own identity card or birth certificate as proof.

iknow = I am aware that any identity theft or false identification may lead to legal prosecution.

infaith = In witness whereof, this Certificate of Declaration is drawn up and issued for all legal intents and purposes.

cert_paceanddate = Done at Mada, on

mothersignature = Mother's signature
