ministry = MINISTRY OF PUBLIC HEALTH
district = MADA HEALTH DISTRICT
reference_number = No. 2382134/DN/FHHM/DSM/MADA
republic = REPUBLIC OF CAMEROON
devise = Peace - Work - Fatherland
cert_title = Birth Certificate
misscatho = MISSION CATHOLIQUE SACRE COEUR
foundation = FONDATION HELVETIQUE DE MADA

label_district=District:

label_structure=Structure:

label_adresse=Address:

label_telephone=Phone:

label_email=Email:

republique_cameroune=REPUBLIC OF CAMEROON

paix_travail_patriee=PEACE - WORK - FATHERLAND

ministere_santee=MINISTRY OF PUBLIC HEALTH

autor = I, the undersigned

bdate = Born on

at = in

birthcertificatenum = Birth Certificate No.

id = Identity Card No.

iborn = Having given birth at the maternity ward of

dateborn = On the date of

icertify = Hereby certify on oath that I have declared my exact identity and presented as proof my own identity card or birth certificate.

iknow = I am aware that any identity theft or false identification shall result in legal proceedings.

infaith = In witness whereof, this Declaration Certificate has been established and issued to serve and avail as the case may be.

cert_paceanddate = Done at 

cert_date = , on

mothersignature = Mother's signature