#Birth certificate of declaration report resource bundle - default (English)

angal.certificatedeclaration.title = BIRTH CERTIFICATE
angal.certificatedeclaration.iam = I, the
angal.certificatedeclaration.bornon = Born on
angal.certificatedeclaration.declaration1 = Having given birth at the maternity of
angal.certificatedeclaration.dateofbirth = Date of birth
angal.certificatedeclaration.declaration2 = Certify on my honor that I have declared my exact identity and presented my own identity document as proof.
angal.certificatedeclaration.declaration3 = I am aware that any identity theft or false identification may lead to legal proceedings.
angal.certificatedeclaration.infaith = In witness whereof this certificate of declaration is issued to serve and be used as required.
angal.certificatedeclaration.doneat = Done at
angal.certificatedeclaration.mothersignature = Signature of the mother
