
misscatho = MISSION CATHOLIQUE SACRE COEUR

autor = I, the undersigned :

cert_title = BIRTH DECLARATION

cert_date = Certifies that the :

cert_place = Place of Declaration

cert_sex = A child of sex :

cert_childname = Named :

cert_sonof = Son / Daughter of :

cert_birthplace = Born at :

cert_motherbirthplace = Born at :

cert_mothername = And the named :

cert_fatherage = Old :

cert_motherage = Old :

cert_profession = Occupation :

cert_residence = Residence :

cert_paceanddate = Place and Date

male = Male

female = Female

years = years



