#Birth declaration report resource bundle - default (English)

angal.declarationbirth.title = BIRTH DECLARATION
angal.declarationbirth.attest1 = I, the undersigned
angal.declarationbirth.attest2 = practicing at
angal.declarationbirth.attest3 = certify that the child
angal.declarationbirth.sex = of sex
angal.declarationbirth.male = Male
angal.declarationbirth.female = Female
angal.declarationbirth.bornon = was born on
angal.declarationbirth.atmaternity = at the maternity of
angal.declarationbirth.sonof = Son/daughter of
angal.declarationbirth.unknown = unknown
angal.declarationbirth.bornat = born at
angal.declarationbirth.agedof = aged
angal.declarationbirth.years = years
angal.declarationbirth.occupation = occupation
angal.declarationbirth.residingat = residing at
angal.declarationbirth.andofnamed = and of the named
angal.declarationbirth.marriagecert = Marriage certificate N°
angal.declarationbirth.dated = dated
angal.declarationbirth.fathercni = Father's ID card N°:
angal.declarationbirth.mothercni = Mother's ID card N°:
angal.declarationbirth.datedon = on
angal.declarationbirth.thedoctor = The doctor,
