angal.report.globalconsumptionreportbyservice.title = Rapport de Consommation Globale par Service

angal.report.globalconsumptionreportbyservice.service = Service

angal.report.globalconsumptionreportbyservice.family = Famille

angal.report.globalconsumptionreportbyservice.cost = Coût

angal.report.globalconsumptionreportbyservice.qty = Qté

angal.report.globalconsumptionreportbyservice.amount = Montant

angal.report.globalconsumptionreportbyservice.total = Total

angal.report.billsreport.from2 = Du

angal.report.billsreport.to2 = Au

angal.report.incomespertype.family = Famille