col_patient=Patient
col_total_court=Total
col_planifiees_court=Plan.
col_realisees_court=Compl.
col_annulees_court=Canc.
col_reportees_court=Post.
col_duree_court=Duration
col_motif_principal=Main Purpose
msg_aucune_visite=No visits for the selected period.