stats_visites_planifiees=Planned Visits
stats_visites_realisees=Completed Visits
stats_visites_annulees=Cancelled Visits
stats_visites_reportees=Postponed Visits
stats_total_patients=Total Patients Followed