
pregnancyReport = Pregnancy Report

patientCode = Patient Code

patientName = Patient Name

pregnancyNumber = Pregnancy Number

totalPregnancy = Total Pregnancies

lmp = LMP

calcDelivery = Calculated Delivery

visitDate = Visit Date

visitNote = Visit Note

visitType = Visit Type

exam = Exam

examResult = Exam Result

examNote = Exam Note

examType = Exam Type

page = Page

on = on