# Locale for report StockSheet.jrxml

angal.stocksheet.date = Date
angal.stocksheet.lotnumber = Lot Number
angal.stocksheet.peremptiondate = Expiry Date
angal.stocksheet.inputquantity = Input Quantity
angal.stocksheet.origin = Origin
angal.stocksheet.outputquantity = Output Quantity
angal.stocksheet.destination = Destination
angal.stocksheet.stockquantity = Stock Quantity
angal.stocksheet.observation = Observation Name/Signature
