jTitle = Admission register

angal.opd.admission.diagnosticdischarge = Diagnosis of discharge
angal.opd.admission.diagnosticentry = Diagnosis of entry
angal.opd.admission.future = Future
angal.opd.admission.numberofday = Number of hospitalization days
angal.opd.admission.relaytreatment = Relay treatment
angal.opd.admission.traitment = Received treatment
angal.opd.register.antecedent = Antecedents
angal.opd.register.case = Case
angal.opd.register.contactandnextkin = Contact and Next kin
angal.opd.register.date = Date
angal.opd.register.examinationrequested = Investigations
angal.opd.register.ispregnant = Pregnant
angal.opd.register.monthorder = N. Month order
angal.opd.register.observation = Observation
angal.opd.register.patientcode = Patient code
angal.opd.register.reference = Referral
angal.opd.register.residence = Residence
angal.opd.register.sexe = Sex
angal.opd.register.status = Status
angal.patient.occupation = Occupation
angal.report.admission.dateofdischarge = Date of discharge
angal.report.admission.dateofentry = Date of entry
angal.report.admission.totalonperiode = Total admission on this period :
angal.report.diseaseslist.of = of
angal.report.diseaseslist.page = Page 
angal.report.opdhistory.age = Age
angal.report.opdhistory.name = Names
angal.stat.admissionpatient.register = ADMISSION REGISTER 
