
title =

date =

idpatient =

biochimie =

monthorder =

name =

sexe =

age =

codepatient =

codeprelevement =

glycemie =

uree =

creatine =

asat =

alat = 

acideurique =

albumine =

sucres =

acetone =

pregnanttest =

results =

blood =

urine =

observation =

bacteriologie =

vaginalexam =

uretralexam =

cluecells =

cellepithbyfield =

leucocytebyfield =

trichomonasvaginalis =

levurebyfield =

floredoderlein =

gardenerellavaginalis =

bacillesdegram =

bacillesdegramneg =

coccidegram =

typeflorevaginale =

leucocytes_wbc =

levuress =

diplocoquedeneisseria =

coccidegramneg =

germeisole =

trouble =

clear =

sanguineous =

cellules_epitheliales =

bacteria_ml =

crystals =

flagella =

enumerationofurinarygerms =

numberofleukocytesperfield =

numberofredcellsperfield =

aspect =

negative =

positive =

bacillaryconcentration =

control =

plasmodiumfalciparum =

plasmodiummalariae =

plasmodiumovale =

plasmodiumvivax =

onchocerca =

loa =

skin =

baar1 =

baar2 =

coprology =

atms =

tms =

num_bill =

reductionrate =

person_order_reduction =

director =

other =

aspectsfinanciers =

parasitology =

sputum =






