
title = List of consultations by period

libheader =

to = To

libRange = Range

numorder = Number

name = Name

age = Age

sexe = Sex

temperature = Temperature

pc = PC

pb = PB

pds = PDS

height = Height

vaccins = Vaccins

diagnostic = Diagnostic

exams = Exams

therapie = Therapie

rdv = RDV

note = Note

nextVisit = Next Visit

totalonperiode = Total on period

page = Page

of = Of

jTitle = OPD Patient History